import type { AppLanguage } from '@/i18n'

export interface LocalShareCopy {
  loading: string
  title: string
  intro: string
  visible: string
  hidden: string
  stop: string
  start: string
  errorTitle: string
  genericError: string
  close: string
  pairingCode: string
  nearby: string
  inbox: string
  history: string
  receiver: string
  receiverEnabled: string
  receiverDisabled: string
  manualAddress: string
  connect: string
  sharingOff: string
  sharingOffHint: string
  searching: string
  searchingHint: string
  trusted: string
  firstConnection: string
  selectSkill: string
  validationHint: string
  searchSkill: string
  noMatches: string
  skillUnit: string
  noDevice: string
  confirmSend: string
  progress: string
  inboxEmpty: string
  inboxEmptyHint: string
  wantsToShare: string
  firstPairing: string
  noDescription: string
  files: string
  pairingHint: string
  acceptOnce: string
  acceptTrust: string
  reject: string
  from: string
  applied: string
  quarantined: string
  targetSpace: string
  inspectDifference: string
  useIncoming: string
  saveCopy: string
  snapshotHint: string
  newSkill: string
  newSkillHint: string
  identical: string
  safeUpdate: string
  conflict: string
  differenceCounts: string
  historyEmpty: string
  historyEmptyHint: string
  sent: string
  received: string
  restored: string
  failed: string
  cancelled: string
  restoreVersion: string
  invalidAddress: string
  noWritableSpace: string
  copySuffix: string
}

const zhCN: LocalShareCopy = {
  loading: '正在读取本地共享状态…',
  title: '本地共享',
  intro: '接收内容先进入隔离区。检查文件差异后，再应用到本机技能空间。',
  visible: '附近设备可见',
  hidden: '当前不可见',
  stop: '停止共享',
  start: '开启 10 分钟',
  errorTitle: '操作未完成',
  genericError: '操作失败，请检查设备状态后重试。',
  close: '关闭',
  pairingCode: '配对码 {code}',
  nearby: '附近设备',
  inbox: '收件箱',
  history: '历史记录',
  receiver: '接收设备',
  receiverEnabled: '选择同一私有网络中的 SooKool 设备',
  receiverDisabled: '开启共享后开始发现设备',
  manualAddress: '手动连接地址',
  connect: '连接',
  sharingOff: '本地共享尚未开启',
  sharingOffHint: '开启后会通过局域网组播发现设备。',
  searching: '正在寻找附近设备',
  searchingHint: '设备会自动出现，也可使用地址连接。',
  trusted: '已信任',
  firstConnection: '首次连接',
  selectSkill: '选择 Skill',
  validationHint: '传输前会校验文件数量、大小与内容哈希',
  searchSkill: '搜索名称、描述或技能空间',
  noMatches: '没有匹配的 Skill',
  skillUnit: '个 Skill',
  noDevice: '尚未选择设备',
  confirmSend: '确认并发送',
  progress: '传输进度',
  inboxEmpty: '收件箱是空的',
  inboxEmptyHint: '新的共享请求会先在这里等待确认与差异检查。',
  wantsToShare: '{device} 想分享 {skill}',
  firstPairing: '首次配对',
  noDescription: '未提供描述',
  files: '{count} 个文件',
  pairingHint: '请与发送方屏幕上的配对码核对一致。',
  acceptOnce: '接收一次',
  acceptTrust: '接收并信任',
  reject: '拒绝',
  from: '来自 {device} · {time}',
  applied: '已应用',
  quarantined: '已隔离接收',
  targetSpace: '目标技能空间',
  inspectDifference: '检查差异',
  useIncoming: '使用接收版本',
  saveCopy: '另存为副本',
  snapshotHint: '覆盖前会自动保存本地快照。',
  newSkill: '目标位置暂无同名 Skill',
  newSkillHint: '可以作为全新 Skill 应用。',
  identical: '内容完全相同',
  safeUpdate: '可安全更新',
  conflict: '本地与接收版本均有变化',
  differenceCounts: '新增 {added} · 修改 {modified} · 删除 {deleted} · 相同 {unchanged}',
  historyEmpty: '还没有流转记录',
  historyEmptyHint: '发送、接收、应用与恢复都会自动留痕。',
  sent: '已发送',
  received: '已接收',
  restored: '已恢复',
  failed: '失败',
  cancelled: '已取消',
  restoreVersion: '恢复此版本',
  invalidAddress: '请输入类似 192.168.1.8:53318 的地址。',
  noWritableSpace: '没有可写入的技能空间。',
  copySuffix: '{skill}-来自-{device}'
}

const enUS: LocalShareCopy = {
  loading: 'Loading Local Share…',
  title: 'Local Share',
  intro:
    'Incoming content stays quarantined until you review its file differences and apply it to a local Skill Space.',
  visible: 'Visible to nearby devices',
  hidden: 'Not visible',
  stop: 'Stop sharing',
  start: 'Share for 10 minutes',
  errorTitle: 'Action not completed',
  genericError: 'The action failed. Check the device status and try again.',
  close: 'Close',
  pairingCode: 'Pairing code {code}',
  nearby: 'Nearby',
  inbox: 'Inbox',
  history: 'History',
  receiver: 'Receiving device',
  receiverEnabled: 'Choose a SooKool device on the same private network',
  receiverDisabled: 'Start sharing to discover nearby devices',
  manualAddress: 'Manual device address',
  connect: 'Connect',
  sharingOff: 'Local Share is off',
  sharingOffHint: 'Start sharing to discover devices over your local network.',
  searching: 'Looking for nearby devices',
  searchingHint: 'Devices appear automatically, or connect with an address.',
  trusted: 'Trusted',
  firstConnection: 'First connection',
  selectSkill: 'Choose Skills',
  validationHint: 'File count, size, and content hashes are verified before transfer',
  searchSkill: 'Search name, description, or Skill Space',
  noMatches: 'No matching Skills',
  skillUnit: 'Skills',
  noDevice: 'No device selected',
  confirmSend: 'Review and send',
  progress: 'Transfer progress',
  inboxEmpty: 'Your inbox is empty',
  inboxEmptyHint: 'New share requests wait here for approval and difference review.',
  wantsToShare: '{device} wants to share {skill}',
  firstPairing: 'First pairing',
  noDescription: 'No description',
  files: '{count} files',
  pairingHint: 'Confirm that this code matches the sender’s screen.',
  acceptOnce: 'Accept once',
  acceptTrust: 'Accept and trust',
  reject: 'Reject',
  from: 'From {device} · {time}',
  applied: 'Applied',
  quarantined: 'Received safely',
  targetSpace: 'Target Skill Space',
  inspectDifference: 'Review differences',
  useIncoming: 'Use incoming version',
  saveCopy: 'Save as copy',
  snapshotHint: 'A local snapshot is saved before replacement.',
  newSkill: 'No Skill with this name exists here',
  newSkillHint: 'It can be applied as a new Skill.',
  identical: 'Contents are identical',
  safeUpdate: 'Safe to update',
  conflict: 'Local and incoming versions both changed',
  differenceCounts: 'Added {added} · Changed {modified} · Deleted {deleted} · Same {unchanged}',
  historyEmpty: 'No transfer history yet',
  historyEmptyHint: 'Sending, receiving, applying, and restoring are recorded automatically.',
  sent: 'Sent',
  received: 'Received',
  restored: 'Restored',
  failed: 'Failed',
  cancelled: 'Cancelled',
  restoreVersion: 'Restore version',
  invalidAddress: 'Enter an address like 192.168.1.8:53318.',
  noWritableSpace: 'No writable Skill Space is available.',
  copySuffix: '{skill}-from-{device}'
}

const zhHK: LocalShareCopy = {
  loading: '正在讀取本機共享狀態…',
  title: '本機共享',
  intro: '接收內容會先進入隔離區。檢查檔案差異後，再套用到本機技能空間。',
  visible: '附近裝置可見',
  hidden: '目前不可見',
  stop: '停止共享',
  start: '開啟 10 分鐘',
  errorTitle: '操作未完成',
  genericError: '操作失敗，請檢查裝置狀態後再試。',
  close: '關閉',
  pairingCode: '配對碼 {code}',
  nearby: '附近裝置',
  inbox: '收件匣',
  history: '歷史記錄',
  receiver: '接收裝置',
  receiverEnabled: '選擇同一私人網絡中的 SooKool 裝置',
  receiverDisabled: '開啟共享後開始尋找裝置',
  manualAddress: '手動連接位址',
  connect: '連接',
  sharingOff: '本機共享尚未開啟',
  sharingOffHint: '開啟後會透過區域網絡群播尋找裝置。',
  searching: '正在尋找附近裝置',
  searchingHint: '裝置會自動出現，也可使用位址連接。',
  trusted: '已信任',
  firstConnection: '首次連接',
  selectSkill: '選擇 Skill',
  validationHint: '傳輸前會驗證檔案數量、大小與內容雜湊',
  searchSkill: '搜尋名稱、描述或技能空間',
  noMatches: '沒有相符的 Skill',
  skillUnit: '個 Skill',
  noDevice: '尚未選擇裝置',
  confirmSend: '確認並傳送',
  progress: '傳輸進度',
  inboxEmpty: '收件匣是空的',
  inboxEmptyHint: '新的共享要求會先在此等候確認與差異檢查。',
  wantsToShare: '{device} 想分享 {skill}',
  firstPairing: '首次配對',
  noDescription: '未提供描述',
  files: '{count} 個檔案',
  pairingHint: '請與傳送方畫面上的配對碼核對一致。',
  acceptOnce: '接收一次',
  acceptTrust: '接收並信任',
  reject: '拒絕',
  from: '來自 {device} · {time}',
  applied: '已套用',
  quarantined: '已隔離接收',
  targetSpace: '目標技能空間',
  inspectDifference: '檢查差異',
  useIncoming: '使用接收版本',
  saveCopy: '另存為副本',
  snapshotHint: '覆蓋前會自動儲存本機快照。',
  newSkill: '目標位置沒有同名 Skill',
  newSkillHint: '可以作為全新 Skill 套用。',
  identical: '內容完全相同',
  safeUpdate: '可安全更新',
  conflict: '本機與接收版本均有變更',
  differenceCounts: '新增 {added} · 修改 {modified} · 刪除 {deleted} · 相同 {unchanged}',
  historyEmpty: '還沒有流轉記錄',
  historyEmptyHint: '傳送、接收、套用與還原都會自動留痕。',
  sent: '已傳送',
  received: '已接收',
  restored: '已還原',
  failed: '失敗',
  cancelled: '已取消',
  restoreVersion: '還原此版本',
  invalidAddress: '請輸入類似 192.168.1.8:53318 的位址。',
  noWritableSpace: '沒有可寫入的技能空間。',
  copySuffix: '{skill}-來自-{device}'
}

const jaJP: LocalShareCopy = {
  loading: 'ローカル共有を読み込み中…',
  title: 'ローカル共有',
  intro:
    '受信内容は隔離領域に保存されます。ファイル差分を確認してからローカルのスキルスペースに適用します。',
  visible: '近くのデバイスに表示中',
  hidden: '非表示',
  stop: '共有を停止',
  start: '10分間共有',
  errorTitle: '操作を完了できませんでした',
  genericError: '操作に失敗しました。デバイスの状態を確認して再試行してください。',
  close: '閉じる',
  pairingCode: 'ペアリングコード {code}',
  nearby: '近くのデバイス',
  inbox: '受信箱',
  history: '履歴',
  receiver: '受信デバイス',
  receiverEnabled: '同じプライベートネットワーク上の SooKool デバイスを選択',
  receiverDisabled: '共有を開始してデバイスを検索',
  manualAddress: 'デバイスアドレス',
  connect: '接続',
  sharingOff: 'ローカル共有はオフです',
  sharingOffHint: '共有を開始するとローカルネットワーク上のデバイスを検索します。',
  searching: '近くのデバイスを検索中',
  searchingHint: 'デバイスは自動表示され、アドレスでも接続できます。',
  trusted: '信頼済み',
  firstConnection: '初回接続',
  selectSkill: 'Skill を選択',
  validationHint: '転送前にファイル数、サイズ、コンテンツハッシュを検証します',
  searchSkill: '名前、説明、スキルスペースを検索',
  noMatches: '一致する Skill はありません',
  skillUnit: '個の Skill',
  noDevice: 'デバイス未選択',
  confirmSend: '確認して送信',
  progress: '転送進捗',
  inboxEmpty: '受信箱は空です',
  inboxEmptyHint: '新しい共有リクエストは確認と差分チェックのためここに表示されます。',
  wantsToShare: '{device} が {skill} を共有しようとしています',
  firstPairing: '初回ペアリング',
  noDescription: '説明なし',
  files: '{count} ファイル',
  pairingHint: '送信側の画面とコードが一致することを確認してください。',
  acceptOnce: '今回のみ受信',
  acceptTrust: '受信して信頼',
  reject: '拒否',
  from: '{device} から · {time}',
  applied: '適用済み',
  quarantined: '隔離済み',
  targetSpace: '適用先スキルスペース',
  inspectDifference: '差分を確認',
  useIncoming: '受信版を使用',
  saveCopy: 'コピーとして保存',
  snapshotHint: '置換前にローカルスナップショットを保存します。',
  newSkill: '同名の Skill はありません',
  newSkillHint: '新しい Skill として適用できます。',
  identical: '内容は同一です',
  safeUpdate: '安全に更新できます',
  conflict: 'ローカル版と受信版の両方が変更されています',
  differenceCounts: '追加 {added} · 変更 {modified} · 削除 {deleted} · 同一 {unchanged}',
  historyEmpty: '転送履歴はありません',
  historyEmptyHint: '送信、受信、適用、復元は自動的に記録されます。',
  sent: '送信済み',
  received: '受信済み',
  restored: '復元済み',
  failed: '失敗',
  cancelled: 'キャンセル済み',
  restoreVersion: 'この版を復元',
  invalidAddress: '192.168.1.8:53318 のようなアドレスを入力してください。',
  noWritableSpace: '書き込み可能なスキルスペースがありません。',
  copySuffix: '{skill}-{device}から'
}

const frFR: LocalShareCopy = {
  loading: 'Chargement du partage local…',
  title: 'Partage local',
  intro:
    'Le contenu reçu reste isolé. Examinez les différences avant de l’appliquer à un espace de compétences local.',
  visible: 'Visible à proximité',
  hidden: 'Non visible',
  stop: 'Arrêter le partage',
  start: 'Partager 10 minutes',
  errorTitle: 'Action non terminée',
  genericError: 'Échec de l’action. Vérifiez l’état de l’appareil et réessayez.',
  close: 'Fermer',
  pairingCode: 'Code de jumelage {code}',
  nearby: 'À proximité',
  inbox: 'Réception',
  history: 'Historique',
  receiver: 'Appareil destinataire',
  receiverEnabled: 'Choisissez un appareil SooKool sur le même réseau privé',
  receiverDisabled: 'Activez le partage pour rechercher des appareils',
  manualAddress: 'Adresse de l’appareil',
  connect: 'Connecter',
  sharingOff: 'Le partage local est désactivé',
  sharingOffHint: 'Activez-le pour rechercher les appareils du réseau local.',
  searching: 'Recherche d’appareils',
  searchingHint: 'Ils apparaissent automatiquement ou via leur adresse.',
  trusted: 'Fiable',
  firstConnection: 'Première connexion',
  selectSkill: 'Choisir des Skills',
  validationHint: 'Le nombre, la taille et les empreintes des fichiers sont vérifiés',
  searchSkill: 'Rechercher un nom, une description ou un espace',
  noMatches: 'Aucun Skill correspondant',
  skillUnit: 'Skills',
  noDevice: 'Aucun appareil choisi',
  confirmSend: 'Vérifier et envoyer',
  progress: 'Progression du transfert',
  inboxEmpty: 'La boîte de réception est vide',
  inboxEmptyHint: 'Les nouvelles demandes attendent ici votre confirmation.',
  wantsToShare: '{device} souhaite partager {skill}',
  firstPairing: 'Premier jumelage',
  noDescription: 'Aucune description',
  files: '{count} fichiers',
  pairingHint: 'Vérifiez que ce code correspond à celui de l’expéditeur.',
  acceptOnce: 'Accepter une fois',
  acceptTrust: 'Accepter et faire confiance',
  reject: 'Refuser',
  from: 'De {device} · {time}',
  applied: 'Appliqué',
  quarantined: 'Reçu et isolé',
  targetSpace: 'Espace cible',
  inspectDifference: 'Examiner les différences',
  useIncoming: 'Utiliser la version reçue',
  saveCopy: 'Enregistrer une copie',
  snapshotHint: 'Un instantané local est créé avant le remplacement.',
  newSkill: 'Aucun Skill du même nom',
  newSkillHint: 'Il peut être appliqué comme nouveau Skill.',
  identical: 'Contenu identique',
  safeUpdate: 'Mise à jour sûre',
  conflict: 'Les deux versions ont changé',
  differenceCounts:
    'Ajoutés {added} · Modifiés {modified} · Supprimés {deleted} · Identiques {unchanged}',
  historyEmpty: 'Aucun historique',
  historyEmptyHint: 'Les envois, réceptions, applications et restaurations sont enregistrés.',
  sent: 'Envoyé',
  received: 'Reçu',
  restored: 'Restauré',
  failed: 'Échec',
  cancelled: 'Annulé',
  restoreVersion: 'Restaurer cette version',
  invalidAddress: 'Saisissez une adresse comme 192.168.1.8:53318.',
  noWritableSpace: 'Aucun espace accessible en écriture.',
  copySuffix: '{skill}-de-{device}'
}

const koKR: LocalShareCopy = {
  loading: '로컬 공유 불러오는 중…',
  title: '로컬 공유',
  intro: '받은 내용은 격리 보관됩니다. 파일 차이를 확인한 뒤 로컬 스킬 공간에 적용하세요.',
  visible: '주변 기기에 표시됨',
  hidden: '표시 안 함',
  stop: '공유 중지',
  start: '10분간 공유',
  errorTitle: '작업을 완료하지 못함',
  genericError: '작업에 실패했습니다. 기기 상태를 확인하고 다시 시도하세요.',
  close: '닫기',
  pairingCode: '페어링 코드 {code}',
  nearby: '주변 기기',
  inbox: '받은 항목',
  history: '기록',
  receiver: '받을 기기',
  receiverEnabled: '같은 사설 네트워크의 SooKool 기기를 선택하세요',
  receiverDisabled: '공유를 시작해 기기를 찾으세요',
  manualAddress: '기기 주소',
  connect: '연결',
  sharingOff: '로컬 공유가 꺼져 있음',
  sharingOffHint: '공유를 시작하면 로컬 네트워크에서 기기를 찾습니다.',
  searching: '주변 기기 찾는 중',
  searchingHint: '기기가 자동으로 나타나며 주소로 연결할 수도 있습니다.',
  trusted: '신뢰함',
  firstConnection: '첫 연결',
  selectSkill: 'Skill 선택',
  validationHint: '전송 전에 파일 수, 크기, 콘텐츠 해시를 검증합니다',
  searchSkill: '이름, 설명 또는 스킬 공간 검색',
  noMatches: '일치하는 Skill 없음',
  skillUnit: '개 Skill',
  noDevice: '선택한 기기 없음',
  confirmSend: '확인 후 보내기',
  progress: '전송 진행률',
  inboxEmpty: '받은 항목이 없습니다',
  inboxEmptyHint: '새 공유 요청은 확인과 차이 검토를 위해 여기에 표시됩니다.',
  wantsToShare: '{device}에서 {skill} 공유 요청',
  firstPairing: '첫 페어링',
  noDescription: '설명 없음',
  files: '파일 {count}개',
  pairingHint: '보내는 기기의 화면과 코드가 같은지 확인하세요.',
  acceptOnce: '한 번 받기',
  acceptTrust: '받고 신뢰하기',
  reject: '거절',
  from: '{device}에서 · {time}',
  applied: '적용됨',
  quarantined: '격리 수신됨',
  targetSpace: '대상 스킬 공간',
  inspectDifference: '차이 확인',
  useIncoming: '받은 버전 사용',
  saveCopy: '사본으로 저장',
  snapshotHint: '교체 전에 로컬 스냅샷을 저장합니다.',
  newSkill: '같은 이름의 Skill이 없음',
  newSkillHint: '새 Skill로 적용할 수 있습니다.',
  identical: '내용이 동일함',
  safeUpdate: '안전하게 업데이트 가능',
  conflict: '로컬 버전과 받은 버전 모두 변경됨',
  differenceCounts: '추가 {added} · 변경 {modified} · 삭제 {deleted} · 동일 {unchanged}',
  historyEmpty: '전송 기록이 없습니다',
  historyEmptyHint: '보내기, 받기, 적용 및 복원이 자동 기록됩니다.',
  sent: '보냄',
  received: '받음',
  restored: '복원됨',
  failed: '실패',
  cancelled: '취소됨',
  restoreVersion: '이 버전 복원',
  invalidAddress: '192.168.1.8:53318 형식의 주소를 입력하세요.',
  noWritableSpace: '쓰기 가능한 스킬 공간이 없습니다.',
  copySuffix: '{skill}-{device}에서'
}

const esES: LocalShareCopy = {
  loading: 'Cargando uso compartido local…',
  title: 'Compartir localmente',
  intro:
    'El contenido recibido queda aislado. Revisa las diferencias antes de aplicarlo a un espacio de Skills local.',
  visible: 'Visible para dispositivos cercanos',
  hidden: 'No visible',
  stop: 'Detener',
  start: 'Compartir 10 minutos',
  errorTitle: 'No se completó la acción',
  genericError: 'La acción falló. Comprueba el dispositivo e inténtalo de nuevo.',
  close: 'Cerrar',
  pairingCode: 'Código de emparejamiento {code}',
  nearby: 'Cercanos',
  inbox: 'Bandeja',
  history: 'Historial',
  receiver: 'Dispositivo receptor',
  receiverEnabled: 'Elige un dispositivo SooKool de la misma red privada',
  receiverDisabled: 'Activa el uso compartido para buscar dispositivos',
  manualAddress: 'Dirección del dispositivo',
  connect: 'Conectar',
  sharingOff: 'El uso compartido está desactivado',
  sharingOffHint: 'Actívalo para buscar dispositivos en la red local.',
  searching: 'Buscando dispositivos',
  searchingHint: 'Aparecen automáticamente o puedes usar una dirección.',
  trusted: 'De confianza',
  firstConnection: 'Primera conexión',
  selectSkill: 'Elegir Skills',
  validationHint: 'Se verifican cantidad, tamaño y hash de los archivos',
  searchSkill: 'Buscar nombre, descripción o espacio',
  noMatches: 'No hay Skills coincidentes',
  skillUnit: 'Skills',
  noDevice: 'Ningún dispositivo elegido',
  confirmSend: 'Revisar y enviar',
  progress: 'Progreso',
  inboxEmpty: 'La bandeja está vacía',
  inboxEmptyHint: 'Las nuevas solicitudes esperan aquí tu confirmación.',
  wantsToShare: '{device} quiere compartir {skill}',
  firstPairing: 'Primer emparejamiento',
  noDescription: 'Sin descripción',
  files: '{count} archivos',
  pairingHint: 'Confirma que el código coincide con la pantalla del remitente.',
  acceptOnce: 'Aceptar una vez',
  acceptTrust: 'Aceptar y confiar',
  reject: 'Rechazar',
  from: 'De {device} · {time}',
  applied: 'Aplicado',
  quarantined: 'Recibido y aislado',
  targetSpace: 'Espacio de destino',
  inspectDifference: 'Revisar diferencias',
  useIncoming: 'Usar versión recibida',
  saveCopy: 'Guardar copia',
  snapshotHint: 'Se guarda una copia local antes de reemplazar.',
  newSkill: 'No existe un Skill con este nombre',
  newSkillHint: 'Puede aplicarse como un Skill nuevo.',
  identical: 'Contenido idéntico',
  safeUpdate: 'Actualización segura',
  conflict: 'Ambas versiones tienen cambios',
  differenceCounts:
    'Añadidos {added} · Cambiados {modified} · Eliminados {deleted} · Iguales {unchanged}',
  historyEmpty: 'Aún no hay historial',
  historyEmptyHint: 'Los envíos, recepciones, aplicaciones y restauraciones se registran.',
  sent: 'Enviado',
  received: 'Recibido',
  restored: 'Restaurado',
  failed: 'Fallido',
  cancelled: 'Cancelado',
  restoreVersion: 'Restaurar versión',
  invalidAddress: 'Introduce una dirección como 192.168.1.8:53318.',
  noWritableSpace: 'No hay un espacio con permiso de escritura.',
  copySuffix: '{skill}-de-{device}'
}

const ptBR: LocalShareCopy = {
  loading: 'Carregando compartilhamento local…',
  title: 'Compartilhamento local',
  intro:
    'O conteúdo recebido fica isolado. Revise as diferenças antes de aplicá-lo a um espaço de Skills local.',
  visible: 'Visível para dispositivos próximos',
  hidden: 'Não visível',
  stop: 'Parar',
  start: 'Compartilhar por 10 minutos',
  errorTitle: 'A ação não foi concluída',
  genericError: 'A ação falhou. Verifique o dispositivo e tente novamente.',
  close: 'Fechar',
  pairingCode: 'Código de pareamento {code}',
  nearby: 'Próximos',
  inbox: 'Caixa de entrada',
  history: 'Histórico',
  receiver: 'Dispositivo receptor',
  receiverEnabled: 'Escolha um dispositivo SooKool na mesma rede privada',
  receiverDisabled: 'Ative o compartilhamento para localizar dispositivos',
  manualAddress: 'Endereço do dispositivo',
  connect: 'Conectar',
  sharingOff: 'O compartilhamento local está desativado',
  sharingOffHint: 'Ative-o para localizar dispositivos na rede local.',
  searching: 'Procurando dispositivos',
  searchingHint: 'Eles aparecem automaticamente ou pelo endereço.',
  trusted: 'Confiável',
  firstConnection: 'Primeira conexão',
  selectSkill: 'Escolher Skills',
  validationHint: 'Quantidade, tamanho e hash dos arquivos são verificados',
  searchSkill: 'Buscar nome, descrição ou espaço',
  noMatches: 'Nenhum Skill encontrado',
  skillUnit: 'Skills',
  noDevice: 'Nenhum dispositivo escolhido',
  confirmSend: 'Revisar e enviar',
  progress: 'Progresso',
  inboxEmpty: 'A caixa de entrada está vazia',
  inboxEmptyHint: 'Novos pedidos aguardam aqui sua confirmação.',
  wantsToShare: '{device} quer compartilhar {skill}',
  firstPairing: 'Primeiro pareamento',
  noDescription: 'Sem descrição',
  files: '{count} arquivos',
  pairingHint: 'Confirme se o código corresponde à tela do remetente.',
  acceptOnce: 'Aceitar uma vez',
  acceptTrust: 'Aceitar e confiar',
  reject: 'Recusar',
  from: 'De {device} · {time}',
  applied: 'Aplicado',
  quarantined: 'Recebido e isolado',
  targetSpace: 'Espaço de destino',
  inspectDifference: 'Revisar diferenças',
  useIncoming: 'Usar versão recebida',
  saveCopy: 'Salvar cópia',
  snapshotHint: 'Um snapshot local é salvo antes da substituição.',
  newSkill: 'Não existe Skill com este nome',
  newSkillHint: 'Pode ser aplicado como um novo Skill.',
  identical: 'Conteúdo idêntico',
  safeUpdate: 'Atualização segura',
  conflict: 'As duas versões foram alteradas',
  differenceCounts:
    'Adicionados {added} · Alterados {modified} · Excluídos {deleted} · Iguais {unchanged}',
  historyEmpty: 'Ainda não há histórico',
  historyEmptyHint: 'Envios, recebimentos, aplicações e restaurações são registrados.',
  sent: 'Enviado',
  received: 'Recebido',
  restored: 'Restaurado',
  failed: 'Falhou',
  cancelled: 'Cancelado',
  restoreVersion: 'Restaurar versão',
  invalidAddress: 'Digite um endereço como 192.168.1.8:53318.',
  noWritableSpace: 'Não há espaço gravável disponível.',
  copySuffix: '{skill}-de-{device}'
}

const ar: LocalShareCopy = {
  loading: 'جارٍ تحميل المشاركة المحلية…',
  title: 'مشاركة محلية',
  intro: 'يبقى المحتوى المستلم في العزل. راجع اختلافات الملفات قبل تطبيقه على مساحة مهارات محلية.',
  visible: 'ظاهر للأجهزة القريبة',
  hidden: 'غير ظاهر',
  stop: 'إيقاف المشاركة',
  start: 'مشاركة لمدة 10 دقائق',
  errorTitle: 'لم تكتمل العملية',
  genericError: 'فشلت العملية. تحقق من حالة الجهاز ثم حاول مرة أخرى.',
  close: 'إغلاق',
  pairingCode: 'رمز الاقتران {code}',
  nearby: 'الأجهزة القريبة',
  inbox: 'الوارد',
  history: 'السجل',
  receiver: 'جهاز الاستقبال',
  receiverEnabled: 'اختر جهاز SooKool على الشبكة الخاصة نفسها',
  receiverDisabled: 'ابدأ المشاركة لاكتشاف الأجهزة',
  manualAddress: 'عنوان الجهاز',
  connect: 'اتصال',
  sharingOff: 'المشاركة المحلية متوقفة',
  sharingOffHint: 'ابدأ المشاركة لاكتشاف أجهزة الشبكة المحلية.',
  searching: 'جارٍ البحث عن أجهزة',
  searchingHint: 'تظهر الأجهزة تلقائياً أو يمكنك استخدام عنوان.',
  trusted: 'موثوق',
  firstConnection: 'اتصال أول',
  selectSkill: 'اختيار المهارات',
  validationHint: 'يتم التحقق من عدد الملفات وحجمها وبصماتها قبل النقل',
  searchSkill: 'ابحث بالاسم أو الوصف أو مساحة المهارات',
  noMatches: 'لا توجد مهارات مطابقة',
  skillUnit: 'مهارات',
  noDevice: 'لم يُحدد جهاز',
  confirmSend: 'مراجعة وإرسال',
  progress: 'تقدم النقل',
  inboxEmpty: 'صندوق الوارد فارغ',
  inboxEmptyHint: 'تنتظر طلبات المشاركة الجديدة هنا للتأكيد والمراجعة.',
  wantsToShare: 'يريد {device} مشاركة {skill}',
  firstPairing: 'إقران أول',
  noDescription: 'لا يوجد وصف',
  files: '{count} ملفات',
  pairingHint: 'تأكد من مطابقة الرمز الظاهر لدى المرسل.',
  acceptOnce: 'قبول مرة واحدة',
  acceptTrust: 'قبول وثقة',
  reject: 'رفض',
  from: 'من {device} · {time}',
  applied: 'تم التطبيق',
  quarantined: 'تم الاستلام والعزل',
  targetSpace: 'مساحة المهارات الهدف',
  inspectDifference: 'مراجعة الاختلافات',
  useIncoming: 'استخدام النسخة المستلمة',
  saveCopy: 'حفظ نسخة',
  snapshotHint: 'تُحفظ لقطة محلية قبل الاستبدال.',
  newSkill: 'لا توجد مهارة بالاسم نفسه',
  newSkillHint: 'يمكن تطبيقها كمهارة جديدة.',
  identical: 'المحتوى متطابق',
  safeUpdate: 'التحديث آمن',
  conflict: 'تغيرت النسختان المحلية والمستلمة',
  differenceCounts: 'مضاف {added} · معدل {modified} · محذوف {deleted} · مطابق {unchanged}',
  historyEmpty: 'لا يوجد سجل نقل بعد',
  historyEmptyHint: 'يتم تسجيل الإرسال والاستلام والتطبيق والاستعادة تلقائياً.',
  sent: 'تم الإرسال',
  received: 'تم الاستلام',
  restored: 'تمت الاستعادة',
  failed: 'فشل',
  cancelled: 'ملغى',
  restoreVersion: 'استعادة النسخة',
  invalidAddress: 'أدخل عنواناً مثل 192.168.1.8:53318.',
  noWritableSpace: 'لا توجد مساحة مهارات قابلة للكتابة.',
  copySuffix: '{skill}-من-{device}'
}

const copies: Record<AppLanguage, LocalShareCopy> = {
  'zh-CN': zhCN,
  'zh-HK': zhHK,
  'en-US': enUS,
  'ja-JP': jaJP,
  'fr-FR': frFR,
  'ko-KR': koKR,
  'es-ES': esES,
  'pt-BR': ptBR,
  ar
}

export function localShareCopy(language: AppLanguage): LocalShareCopy {
  return copies[language]
}

export function fillLocalShareCopy(
  template: string,
  values: Record<string, string | number>
): string {
  return template.replace(/\{([^}]+)\}/g, (_, key: string) => String(values[key] ?? `{${key}}`))
}
