import type { AppLanguage } from '@/i18n'

const en = {
  subtitle: 'Discover, preview, and install trusted Agent Skills in the apps you use.', manage: 'Manage sources', searchPlaceholder: 'Search Skills, tasks, authors, or tags', clear: 'Clear search', publicSearch: 'Search all markets', sourcesAria: 'Market sources', builtin: 'Built in', sortFeatured: 'Featured', sortName: 'Name', sortSource: 'Source', loading: 'Loading {name}', loadingHint: 'The first remote load may take a few seconds.', catalog: 'market catalog', publicResults: 'All-market search', publicDescription: 'Results from all configured sources and skills.sh', count: '{count} Skills', emptyTitle: 'No matching Skills', emptyBody: 'Try another category or keyword, or search all markets.', pagination: 'Skill list pagination', pageSummary: 'Page {page} of {pages} · {total} Skills', previous: 'Previous', next: 'Next', files: '{count} files', preview: 'Preview', back: 'Back to market', installTo: 'Install to…', reinstallTo: 'Reinstall to…', overview: 'Overview', content: 'Skill content', fileTab: 'Files {count}', reading: 'Reading Skill safely…', unavailable: 'Preview is temporarily unavailable.', source: 'Source', status: 'Install status', scripts: 'Scripts', hasScripts: 'Contains scripts', noScripts: 'No scripts', tags: 'Tags', checks: 'Pre-install checks', safe: 'No structural warnings found. Read the Skill content before installing.', openSource: 'Open source page', unsupported: 'This file type cannot be previewed', selectFile: 'Select a file to preview', chooseLocation: 'Choose install location', multiTarget: 'Install to multiple detected apps at once', noTargets: 'No supported local apps detected.', global: 'Global install', project: 'Install in project', chooseProject: 'Choose project folder…', copy: 'Copy independent files', copyHint: 'When off, symbolic links make later updates easier', installing: 'Installing…', installApps: 'Install to {count} apps', manageTitle: 'Manage market sources', manageBody: 'Aggregate Git repositories and local Skill folders. One failed source will not affect the others.', deleteSource: 'Delete source', sourceAddress: 'Source address', displayName: 'Display name', optional: 'Optional', add: 'Add and check', installedTo: 'Installed to {names}', partialFailure: '{count} market sources are unavailable; other content loaded normally.'
}

type Copy = typeof en
const zhs: Copy = { ...en, subtitle:'发现、预览并把可靠的 Agent Skill 安装到你正在使用的应用。',manage:'管理市场源',searchPlaceholder:'搜索 Skill、任务、作者或标签',clear:'清空搜索',publicSearch:'搜索全部市场',sourcesAria:'市场来源',builtin:'内置',sortFeatured:'推荐排序',sortName:'按名称',sortSource:'按来源',loading:'正在加载 {name}',loadingHint:'首次读取远程市场可能需要几秒。',catalog:'市场目录',publicResults:'全市场搜索',publicDescription:'来自全部已配置市场与 skills.sh 的聚合结果',count:'{count} 个 Skill',emptyTitle:'这里还没有匹配的 Skill',emptyBody:'换一个分类或关键词，再搜索全部市场。',pagination:'Skill 列表分页',pageSummary:'第 {page} / {pages} 页 · 共 {total} 个 Skill',previous:'上一页',next:'下一页',files:'{count} 个文件',preview:'预览',back:'返回市场',installTo:'安装到…',reinstallTo:'重新安装到…',overview:'概览',content:'Skill 内容',fileTab:'文件 {count}',reading:'正在安全地读取 Skill…',unavailable:'暂时无法读取预览内容。',source:'来源',status:'安装状态',scripts:'脚本',hasScripts:'包含脚本',noScripts:'无脚本',tags:'标签',checks:'安装前检查',safe:'未发现结构性警告，仍建议阅读 Skill 内容后再安装。',openSource:'打开来源页面',unsupported:'此文件类型不支持直接预览',selectFile:'选择一个文件进行预览',chooseLocation:'选择安装位置',multiTarget:'可同时安装到多个已检测应用',noTargets:'未检测到支持的本地应用。',global:'全局安装',project:'安装到项目',chooseProject:'选择项目目录…',copy:'复制独立文件',copyHint:'关闭时使用符号链接，后续更新更方便',installing:'正在安装…',installApps:'安装到 {count} 个应用',manageTitle:'管理市场源',manageBody:'聚合 Git 仓库和本地 Skill 目录。单个来源失败不会影响其他市场。',deleteSource:'删除来源',sourceAddress:'来源地址',displayName:'显示名称',optional:'可选',add:'添加并检查',installedTo:'已安装到 {names}',partialFailure:'{count} 个市场源暂时不可用，其余内容已正常加载。' }
const zht: Copy = { ...en, subtitle:'探索、預覽並將可靠的 Agent Skill 安裝到你使用的應用程式。',manage:'管理市集來源',searchPlaceholder:'搜尋 Skill、任務、作者或標籤',clear:'清除搜尋',publicSearch:'搜尋公開市集',sourcesAria:'市集來源',builtin:'內建',sortFeatured:'推薦排序',sortName:'依名稱',sortSource:'依來源',loading:'正在載入 {name}',loadingHint:'首次讀取遠端市集可能需要數秒。',catalog:'市集目錄',publicResults:'公開搜尋',publicDescription:'來自 skills.sh 的公開結果',count:'{count} 個 Skill',emptyTitle:'沒有符合的 Skill',emptyBody:'請嘗試其他分類或關鍵字，或搜尋公開市集。',pagination:'Skill 清單分頁',pageSummary:'第 {page} / {pages} 頁 · 共 {total} 個 Skill',previous:'上一頁',next:'下一頁',files:'{count} 個檔案',preview:'預覽',back:'返回市集',installTo:'安裝到…',reinstallTo:'重新安裝到…',overview:'概覽',content:'Skill 內容',fileTab:'檔案 {count}',reading:'正在安全讀取 Skill…',unavailable:'暫時無法讀取預覽。',source:'來源',status:'安裝狀態',scripts:'腳本',hasScripts:'包含腳本',noScripts:'無腳本',tags:'標籤',checks:'安裝前檢查',safe:'未發現結構警告，仍建議先閱讀 Skill 內容。',openSource:'開啟來源頁面',unsupported:'此檔案類型無法直接預覽',selectFile:'選擇要預覽的檔案',chooseLocation:'選擇安裝位置',multiTarget:'可同時安裝到多個已偵測應用程式',noTargets:'未偵測到支援的本機應用程式。',global:'全域安裝',project:'安裝到專案',chooseProject:'選擇專案資料夾…',copy:'複製獨立檔案',copyHint:'關閉時使用符號連結，後續更新更方便',installing:'正在安裝…',installApps:'安裝到 {count} 個應用程式',manageTitle:'管理市集來源',manageBody:'彙整 Git 儲存庫與本機 Skill 資料夾。單一來源失敗不影響其他市集。',deleteSource:'刪除來源',sourceAddress:'來源位址',displayName:'顯示名稱',optional:'選填',add:'新增並檢查',installedTo:'已安裝到 {names}',partialFailure:'{count} 個市集來源暫時無法使用，其餘內容已正常載入。' }
const ja: Copy = { ...en, subtitle:'信頼できる Agent Skill を見つけ、プレビューして、使用中のアプリにインストールします。',manage:'ソースを管理',searchPlaceholder:'Skill、タスク、作者、タグを検索',clear:'検索をクリア',publicSearch:'公開マーケットを検索',sourcesAria:'マーケットソース',builtin:'内蔵',sortFeatured:'おすすめ順',sortName:'名前順',sortSource:'ソース順',loading:'{name} を読み込み中',loadingHint:'初回のリモート読み込みには数秒かかる場合があります。',catalog:'マーケットカタログ',publicResults:'公開検索',publicDescription:'skills.sh の公開検索結果',count:'{count} 件の Skill',emptyTitle:'一致する Skill はありません',emptyBody:'別のカテゴリやキーワードを試すか、公開マーケットを検索してください。',pagination:'Skill 一覧のページ',pageSummary:'{page} / {pages} ページ · 全 {total} 件',previous:'前へ',next:'次へ',files:'{count} ファイル',preview:'プレビュー',back:'マーケットに戻る',installTo:'インストール先…',reinstallTo:'再インストール先…',overview:'概要',content:'Skill 内容',fileTab:'ファイル {count}',reading:'Skill を安全に読み込み中…',unavailable:'現在プレビューを読み込めません。',source:'ソース',status:'インストール状態',scripts:'スクリプト',hasScripts:'スクリプトあり',noScripts:'スクリプトなし',tags:'タグ',checks:'インストール前チェック',safe:'構造上の警告はありません。インストール前に内容を確認してください。',openSource:'ソースページを開く',unsupported:'このファイル形式はプレビューできません',selectFile:'プレビューするファイルを選択',chooseLocation:'インストール先を選択',multiTarget:'検出済みの複数アプリへ同時にインストールできます',noTargets:'対応するローカルアプリが見つかりません。',global:'グローバル',project:'プロジェクトへ',chooseProject:'プロジェクトフォルダーを選択…',copy:'独立ファイルをコピー',copyHint:'オフの場合はシンボリックリンクで更新しやすくします',installing:'インストール中…',installApps:'{count} 個のアプリにインストール',manageTitle:'マーケットソースを管理',manageBody:'Git リポジトリとローカル Skill フォルダーを集約します。個別の失敗は他に影響しません。',deleteSource:'ソースを削除',sourceAddress:'ソースアドレス',displayName:'表示名',optional:'任意',add:'追加して確認',installedTo:'{names} にインストールしました',partialFailure:'{count} 個のソースを利用できません。他の内容は正常に読み込まれました。' }
const ko: Copy = { ...en, subtitle:'신뢰할 수 있는 Agent Skill을 검색하고 미리 본 뒤 사용 중인 앱에 설치하세요.',manage:'소스 관리',searchPlaceholder:'Skill, 작업, 작성자 또는 태그 검색',clear:'검색 지우기',publicSearch:'공개 마켓 검색',sourcesAria:'마켓 소스',builtin:'내장',sortFeatured:'추천순',sortName:'이름순',sortSource:'소스순',loading:'{name} 불러오는 중',loadingHint:'첫 원격 로드에는 몇 초가 걸릴 수 있습니다.',catalog:'마켓 카탈로그',publicResults:'공개 검색',publicDescription:'skills.sh 공개 결과',count:'Skill {count}개',emptyTitle:'일치하는 Skill이 없습니다',emptyBody:'다른 분류나 키워드를 사용하거나 공개 마켓을 검색하세요.',pagination:'Skill 목록 페이지',pageSummary:'{page} / {pages}페이지 · 총 {total}개',previous:'이전',next:'다음',files:'파일 {count}개',preview:'미리 보기',back:'마켓으로',installTo:'설치 위치…',reinstallTo:'다시 설치…',overview:'개요',content:'Skill 내용',fileTab:'파일 {count}',reading:'Skill을 안전하게 읽는 중…',unavailable:'미리 보기를 불러올 수 없습니다.',source:'소스',status:'설치 상태',scripts:'스크립트',hasScripts:'스크립트 포함',noScripts:'스크립트 없음',tags:'태그',checks:'설치 전 확인',safe:'구조적 경고가 없습니다. 설치 전에 내용을 확인하세요.',openSource:'소스 페이지 열기',unsupported:'이 파일 형식은 미리 볼 수 없습니다',selectFile:'미리 볼 파일 선택',chooseLocation:'설치 위치 선택',multiTarget:'감지된 여러 앱에 동시에 설치할 수 있습니다',noTargets:'지원되는 로컬 앱이 없습니다.',global:'전역 설치',project:'프로젝트에 설치',chooseProject:'프로젝트 폴더 선택…',copy:'독립 파일 복사',copyHint:'끄면 심볼릭 링크를 사용해 업데이트가 쉬워집니다',installing:'설치 중…',installApps:'앱 {count}개에 설치',manageTitle:'마켓 소스 관리',manageBody:'Git 저장소와 로컬 Skill 폴더를 모읍니다. 개별 실패는 다른 마켓에 영향을 주지 않습니다.',deleteSource:'소스 삭제',sourceAddress:'소스 주소',displayName:'표시 이름',optional:'선택 사항',add:'추가 및 확인',installedTo:'{names}에 설치됨',partialFailure:'소스 {count}개를 사용할 수 없습니다. 나머지는 정상적으로 로드되었습니다.' }

const fr: Copy = { ...en, subtitle:'Découvrez, prévisualisez et installez des Agent Skills fiables dans vos applications.',manage:'Gérer les sources',searchPlaceholder:'Rechercher des Skills, tâches, auteurs ou tags',clear:'Effacer la recherche',publicSearch:'Rechercher sur le marché public',sourcesAria:'Sources du marché',builtin:'Intégrée',sortFeatured:'Recommandées',sortName:'Par nom',sortSource:'Par source',loading:'Chargement de {name}',loadingHint:'Le premier chargement distant peut prendre quelques secondes.',catalog:'catalogue du marché',publicResults:'Recherche publique',publicDescription:'Résultats publics de skills.sh',count:'{count} Skills',emptyTitle:'Aucune Skill correspondante',emptyBody:'Essayez une autre catégorie ou un autre mot-clé.',pagination:'Pagination des Skills',pageSummary:'Page {page} sur {pages} · {total} Skills',previous:'Précédent',next:'Suivant',files:'{count} fichiers',preview:'Aperçu',back:'Retour au marché',installTo:'Installer dans…',reinstallTo:'Réinstaller dans…',overview:'Aperçu',content:'Contenu de la Skill',fileTab:'Fichiers {count}',reading:'Lecture sécurisée de la Skill…',unavailable:'Aperçu temporairement indisponible.',source:'Source',status:'État de l’installation',scripts:'Scripts',hasScripts:'Contient des scripts',noScripts:'Aucun script',tags:'Tags',checks:'Vérifications avant installation',safe:'Aucun avertissement structurel. Lisez le contenu avant l’installation.',openSource:'Ouvrir la page source',unsupported:'Ce type de fichier ne peut pas être prévisualisé',selectFile:'Sélectionnez un fichier à prévisualiser',chooseLocation:'Choisir l’emplacement',multiTarget:'Installation simultanée dans plusieurs applications détectées',noTargets:'Aucune application locale compatible détectée.',global:'Installation globale',project:'Installer dans le projet',chooseProject:'Choisir le dossier du projet…',copy:'Copier des fichiers indépendants',copyHint:'Sinon, les liens symboliques facilitent les mises à jour',installing:'Installation…',installApps:'Installer dans {count} applications',manageTitle:'Gérer les sources du marché',manageBody:'Regroupe les dépôts Git et dossiers Skill locaux. Une source défaillante n’affecte pas les autres.',deleteSource:'Supprimer la source',sourceAddress:'Adresse de la source',displayName:'Nom affiché',optional:'Facultatif',add:'Ajouter et vérifier',installedTo:'Installée dans {names}',partialFailure:'{count} sources sont indisponibles ; les autres contenus ont été chargés.' }
const es: Copy = { ...en, subtitle:'Descubre, previsualiza e instala Agent Skills fiables en tus aplicaciones.',manage:'Gestionar fuentes',searchPlaceholder:'Buscar Skills, tareas, autores o etiquetas',clear:'Borrar búsqueda',publicSearch:'Buscar en el mercado público',sourcesAria:'Fuentes del mercado',builtin:'Integrada',sortFeatured:'Recomendadas',sortName:'Por nombre',sortSource:'Por fuente',loading:'Cargando {name}',loadingHint:'La primera carga remota puede tardar unos segundos.',catalog:'catálogo del mercado',publicResults:'Búsqueda pública',publicDescription:'Resultados públicos de skills.sh',count:'{count} Skills',emptyTitle:'No hay Skills coincidentes',emptyBody:'Prueba otra categoría o palabra clave.',pagination:'Paginación de Skills',pageSummary:'Página {page} de {pages} · {total} Skills',previous:'Anterior',next:'Siguiente',files:'{count} archivos',preview:'Vista previa',back:'Volver al mercado',installTo:'Instalar en…',reinstallTo:'Reinstalar en…',overview:'Resumen',content:'Contenido de la Skill',fileTab:'Archivos {count}',reading:'Leyendo la Skill de forma segura…',unavailable:'La vista previa no está disponible.',source:'Fuente',status:'Estado de instalación',scripts:'Scripts',hasScripts:'Contiene scripts',noScripts:'Sin scripts',tags:'Etiquetas',checks:'Comprobaciones previas',safe:'No hay advertencias estructurales. Lee el contenido antes de instalar.',openSource:'Abrir página de origen',unsupported:'Este tipo de archivo no se puede previsualizar',selectFile:'Selecciona un archivo para previsualizar',chooseLocation:'Elegir ubicación de instalación',multiTarget:'Instala en varias aplicaciones detectadas a la vez',noTargets:'No se detectaron aplicaciones locales compatibles.',global:'Instalación global',project:'Instalar en proyecto',chooseProject:'Elegir carpeta del proyecto…',copy:'Copiar archivos independientes',copyHint:'Si se desactiva, los enlaces simbólicos facilitan las actualizaciones',installing:'Instalando…',installApps:'Instalar en {count} aplicaciones',manageTitle:'Gestionar fuentes del mercado',manageBody:'Agrupa repositorios Git y carpetas Skill locales. Un fallo no afecta a las demás fuentes.',deleteSource:'Eliminar fuente',sourceAddress:'Dirección de la fuente',displayName:'Nombre visible',optional:'Opcional',add:'Añadir y comprobar',installedTo:'Instalada en {names}',partialFailure:'{count} fuentes no están disponibles; el resto se cargó correctamente.' }
const pt: Copy = { ...en, subtitle:'Descubra, visualize e instale Agent Skills confiáveis nos seus aplicativos.',manage:'Gerenciar fontes',searchPlaceholder:'Buscar Skills, tarefas, autores ou tags',clear:'Limpar busca',publicSearch:'Buscar no mercado público',sourcesAria:'Fontes do mercado',builtin:'Integrada',sortFeatured:'Recomendadas',sortName:'Por nome',sortSource:'Por fonte',loading:'Carregando {name}',loadingHint:'O primeiro carregamento remoto pode levar alguns segundos.',catalog:'catálogo do mercado',publicResults:'Busca pública',publicDescription:'Resultados públicos do skills.sh',count:'{count} Skills',emptyTitle:'Nenhuma Skill correspondente',emptyBody:'Tente outra categoria ou palavra-chave.',pagination:'Paginação de Skills',pageSummary:'Página {page} de {pages} · {total} Skills',previous:'Anterior',next:'Próxima',files:'{count} arquivos',preview:'Visualizar',back:'Voltar ao mercado',installTo:'Instalar em…',reinstallTo:'Reinstalar em…',overview:'Visão geral',content:'Conteúdo da Skill',fileTab:'Arquivos {count}',reading:'Lendo a Skill com segurança…',unavailable:'Prévia temporariamente indisponível.',source:'Fonte',status:'Status da instalação',scripts:'Scripts',hasScripts:'Contém scripts',noScripts:'Sem scripts',tags:'Tags',checks:'Verificações antes da instalação',safe:'Nenhum alerta estrutural. Leia o conteúdo antes de instalar.',openSource:'Abrir página da fonte',unsupported:'Este tipo de arquivo não pode ser visualizado',selectFile:'Selecione um arquivo para visualizar',chooseLocation:'Escolher local de instalação',multiTarget:'Instale em vários aplicativos detectados ao mesmo tempo',noTargets:'Nenhum aplicativo local compatível detectado.',global:'Instalação global',project:'Instalar no projeto',chooseProject:'Escolher pasta do projeto…',copy:'Copiar arquivos independentes',copyHint:'Desativado, links simbólicos facilitam atualizações',installing:'Instalando…',installApps:'Instalar em {count} aplicativos',manageTitle:'Gerenciar fontes do mercado',manageBody:'Agrupa repositórios Git e pastas Skill locais. Uma falha não afeta as outras fontes.',deleteSource:'Excluir fonte',sourceAddress:'Endereço da fonte',displayName:'Nome exibido',optional:'Opcional',add:'Adicionar e verificar',installedTo:'Instalada em {names}',partialFailure:'{count} fontes indisponíveis; o restante foi carregado normalmente.' }
const arabic: Copy = { ...en, subtitle:'اكتشف مهارات Agent الموثوقة وعاينها وثبتها في تطبيقاتك.',manage:'إدارة المصادر',searchPlaceholder:'البحث عن المهارات أو المهام أو المؤلفين أو الوسوم',clear:'مسح البحث',publicSearch:'البحث في السوق العام',sourcesAria:'مصادر السوق',builtin:'مدمج',sortFeatured:'الموصى بها',sortName:'حسب الاسم',sortSource:'حسب المصدر',loading:'جار تحميل {name}',loadingHint:'قد يستغرق التحميل البعيد الأول بضع ثوان.',catalog:'دليل السوق',publicResults:'بحث عام',publicDescription:'نتائج عامة من skills.sh',count:'{count} Skill',emptyTitle:'لا توجد مهارات مطابقة',emptyBody:'جرب فئة أو كلمة مفتاحية أخرى.',pagination:'صفحات قائمة المهارات',pageSummary:'الصفحة {page} من {pages} · المجموع {total}',previous:'السابق',next:'التالي',files:'{count} ملفات',preview:'معاينة',back:'العودة إلى السوق',installTo:'تثبيت في…',reinstallTo:'إعادة التثبيت في…',overview:'نظرة عامة',content:'محتوى Skill',fileTab:'الملفات {count}',reading:'جار قراءة Skill بأمان…',unavailable:'المعاينة غير متاحة مؤقتا.',source:'المصدر',status:'حالة التثبيت',scripts:'البرامج النصية',hasScripts:'تتضمن برامج نصية',noScripts:'لا توجد برامج نصية',tags:'الوسوم',checks:'فحوصات ما قبل التثبيت',safe:'لا توجد تحذيرات بنيوية. اقرأ المحتوى قبل التثبيت.',openSource:'فتح صفحة المصدر',unsupported:'لا يمكن معاينة هذا النوع من الملفات',selectFile:'اختر ملفا للمعاينة',chooseLocation:'اختر موقع التثبيت',multiTarget:'يمكن التثبيت في عدة تطبيقات مكتشفة معا',noTargets:'لم يتم اكتشاف تطبيقات محلية مدعومة.',global:'تثبيت عام',project:'تثبيت في المشروع',chooseProject:'اختر مجلد المشروع…',copy:'نسخ ملفات مستقلة',copyHint:'عند الإيقاف تسهل الروابط الرمزية التحديثات',installing:'جار التثبيت…',installApps:'التثبيت في {count} تطبيقات',manageTitle:'إدارة مصادر السوق',manageBody:'يجمع مستودعات Git ومجلدات Skill المحلية. فشل مصدر لا يؤثر في غيره.',deleteSource:'حذف المصدر',sourceAddress:'عنوان المصدر',displayName:'اسم العرض',optional:'اختياري',add:'إضافة وفحص',installedTo:'تم التثبيت في {names}',partialFailure:'تعذر استخدام {count} مصادر؛ تم تحميل الباقي بنجاح.' }
const copies: Record<AppLanguage, Copy> = { 'zh-CN':zhs, 'zh-TW':zht, 'en-US':en, 'ja-JP':ja, 'ko-KR':ko, 'fr-FR':fr, 'es-ES':es, 'pt-BR':pt, ar:arabic }
const allMarketSearchCopy: Record<AppLanguage, Pick<Copy, 'publicSearch' | 'publicResults' | 'publicDescription' | 'emptyBody'>> = {
  'zh-CN': { publicSearch:'搜索全部市场', publicResults:'全市场搜索', publicDescription:'来自全部已配置市场与 skills.sh 的聚合结果', emptyBody:'换一个分类或关键词，再搜索全部市场。' },
  'zh-TW': { publicSearch:'搜尋全部市集', publicResults:'全市集搜尋', publicDescription:'來自所有已設定市集與 skills.sh 的彙整結果', emptyBody:'請嘗試其他分類或關鍵字，再搜尋全部市集。' },
  'en-US': { publicSearch:'Search all markets', publicResults:'All-market search', publicDescription:'Results from all configured sources and skills.sh', emptyBody:'Try another category or keyword, then search all markets.' },
  'ja-JP': { publicSearch:'すべてのマーケットを検索', publicResults:'全マーケット検索', publicDescription:'設定済みの全ソースと skills.sh の統合結果', emptyBody:'別のカテゴリやキーワードで全マーケットを検索してください。' },
  'ko-KR': { publicSearch:'모든 마켓 검색', publicResults:'전체 마켓 검색', publicDescription:'설정된 모든 소스와 skills.sh의 통합 결과', emptyBody:'다른 분류나 키워드로 모든 마켓을 검색하세요.' },
  'fr-FR': { publicSearch:'Rechercher sur tous les marchés', publicResults:'Recherche globale', publicDescription:'Résultats de toutes les sources configurées et de skills.sh', emptyBody:'Essayez une autre catégorie ou recherchez sur tous les marchés.' },
  'es-ES': { publicSearch:'Buscar en todos los mercados', publicResults:'Búsqueda global', publicDescription:'Resultados de todas las fuentes configuradas y skills.sh', emptyBody:'Prueba otra categoría o busca en todos los mercados.' },
  'pt-BR': { publicSearch:'Buscar em todos os mercados', publicResults:'Busca global', publicDescription:'Resultados de todas as fontes configuradas e do skills.sh', emptyBody:'Tente outra categoria ou busque em todos os mercados.' },
  ar: { publicSearch:'البحث في جميع الأسواق', publicResults:'بحث شامل', publicDescription:'نتائج جميع المصادر المهيأة و skills.sh', emptyBody:'جرب فئة أخرى أو ابحث في جميع الأسواق.' }
}
const searchScopeCopy: Record<AppLanguage, { label: string; allMarkets: string }> = {
  'zh-CN': { label: '当前搜索范围', allMarkets: '全部已配置市场 + skills.sh' },
  'zh-TW': { label: '目前搜尋範圍', allMarkets: '所有已設定市集 + skills.sh' },
  'en-US': { label: 'Current search scope', allMarkets: 'All configured markets + skills.sh' },
  'ja-JP': { label: '現在の検索範囲', allMarkets: '設定済みの全マーケット + skills.sh' },
  'ko-KR': { label: '현재 검색 범위', allMarkets: '설정된 모든 마켓 + skills.sh' },
  'fr-FR': { label: 'Périmètre actuel', allMarkets: 'Tous les marchés configurés + skills.sh' },
  'es-ES': { label: 'Ámbito de búsqueda', allMarkets: 'Todos los mercados configurados + skills.sh' },
  'pt-BR': { label: 'Escopo da busca', allMarkets: 'Todos os mercados configurados + skills.sh' },
  ar: { label: 'نطاق البحث الحالي', allMarkets: 'جميع الأسواق المهيأة + skills.sh' }
}

export function marketCopy(language: AppLanguage): Copy { return { ...copies[language], ...allMarketSearchCopy[language] } }
export function unknownFileCountCopy(language: AppLanguage): string {
  const labels: Record<AppLanguage, string> = {
    'zh-CN': '未获取',
    'zh-TW': '未取得',
    'en-US': 'Not fetched',
    'ja-JP': '未取得',
    'ko-KR': '가져오지 않음',
    'fr-FR': 'Non récupéré',
    'es-ES': 'No obtenido',
    'pt-BR': 'Não obtido',
    ar: 'لم يتم الجلب'
  }
  return labels[language]
}
export function marketPaletteCopy(language: AppLanguage): { label: string; names: Record<MarketPaletteName, string> } {
  const labels: Record<AppLanguage, [string, string, string, string, string, string, string]> = {
    'zh-CN': ['色系', '孟菲斯', '马卡龙', '洛可可', '蒙德里安', '莫兰迪', '马蒂斯'],
    'zh-TW': ['色系', '孟菲斯', '馬卡龍', '洛可可', '蒙德里安', '莫蘭迪', '馬蒂斯'],
    'en-US': ['Palette', 'Memphis', 'Macaron', 'Rococo', 'Mondrian', 'Morandi', 'Matisse'],
    'ja-JP': ['カラーパレット', 'メンフィス', 'マカロン', 'ロココ', 'モンドリアン', 'モランディ', 'マティス'],
    'ko-KR': ['색상 팔레트', '멤피스', '마카롱', '로코코', '몬드리안', '모란디', '마티스'],
    'fr-FR': ['Palette', 'Memphis', 'Macaron', 'Rococo', 'Mondrian', 'Morandi', 'Matisse'],
    'es-ES': ['Paleta', 'Memphis', 'Macaron', 'Rococó', 'Mondrian', 'Morandi', 'Matisse'],
    'pt-BR': ['Paleta', 'Memphis', 'Macaron', 'Rococó', 'Mondrian', 'Morandi', 'Matisse'],
    ar: ['لوحة الألوان', 'ممفيس', 'ماكرون', 'روكوكو', 'موندريان', 'موراندي', 'ماتيس']
  }
  const [label, memphis, macaron, rococo, mondrian, morandi, matisse] = labels[language]
  return { label, names: { memphis, macaron, rococo, mondrian, morandi, matisse } }
}
type MarketPaletteName = 'memphis' | 'macaron' | 'rococo' | 'mondrian' | 'morandi' | 'matisse'
export function marketSearchScopeCopy(language: AppLanguage): { label: string; allMarkets: string } { return searchScopeCopy[language] }
export function marketText(template: string, values: Record<string, string | number>): string { return Object.entries(values).reduce((text,[key,value]) => text.replaceAll(`{${key}}`,String(value)),template) }
export function localizedInstallStatus(language: AppLanguage, installed: boolean): string {
  const values: Record<AppLanguage, [string,string]> = {
    'zh-CN':['已安装','未安装'],'zh-TW':['已安裝','未安裝'],'en-US':['Installed','Not installed'],'ja-JP':['インストール済み','未インストール'],'fr-FR':['Installée','Non installée'],'ko-KR':['설치됨','설치 안 됨'],'es-ES':['Instalada','No instalada'],'pt-BR':['Instalada','Não instalada'],ar:['مثبتة','غير مثبتة']
  }
  return values[language][installed ? 0 : 1]
}
export function fileViewLabels(language: AppLanguage): { preview: string; source: string } {
  const values: Record<AppLanguage, [string,string]> = {
    'zh-CN':['预览','源码'],'zh-TW':['預覽','原始碼'],'en-US':['Preview','Source'],'ja-JP':['プレビュー','ソース'],'fr-FR':['Aperçu','Source'],'ko-KR':['미리 보기','소스'],'es-ES':['Vista previa','Código'],'pt-BR':['Visualizar','Código'],ar:['معاينة','المصدر']
  }
  const [preview,source]=values[language]
  return { preview,source }
}

type WarningCode = 'scripts' | 'binary' | 'missingFrontmatter' | 'unterminatedFrontmatter' | 'invalidYaml' | 'objectRequired' | 'missingName' | 'missingDescription'
const warningMessages: Record<AppLanguage, Record<WarningCode,string>> = {
  'zh-CN': { scripts:'此 Skill 包含脚本文件。安装前请检查脚本内容。',binary:'此 Skill 包含无法直接预览的二进制文件。',missingFrontmatter:'缺少 YAML frontmatter。',unterminatedFrontmatter:'frontmatter 没有正确结束。',invalidYaml:'YAML frontmatter 无效。',objectRequired:'YAML frontmatter 必须是键值对象。',missingName:'frontmatter 缺少 name。',missingDescription:'frontmatter 缺少 description。' },
  'zh-TW': { scripts:'此 Skill 包含腳本檔案。安裝前請檢查腳本內容。',binary:'此 Skill 包含無法直接預覽的二進位檔案。',missingFrontmatter:'缺少 YAML frontmatter。',unterminatedFrontmatter:'frontmatter 未正確結束。',invalidYaml:'YAML frontmatter 無效。',objectRequired:'YAML frontmatter 必須是鍵值物件。',missingName:'frontmatter 缺少 name。',missingDescription:'frontmatter 缺少 description。' },
  'en-US': { scripts:'This Skill contains script files. Review them before installation.',binary:'This Skill contains binary files that cannot be previewed.',missingFrontmatter:'YAML frontmatter is missing.',unterminatedFrontmatter:'The frontmatter is not properly terminated.',invalidYaml:'The YAML frontmatter is invalid.',objectRequired:'YAML frontmatter must be a key-value object.',missingName:'The frontmatter is missing name.',missingDescription:'The frontmatter is missing description.' },
  'ja-JP': { scripts:'この Skill にはスクリプトが含まれます。インストール前に確認してください。',binary:'この Skill にはプレビューできないバイナリファイルが含まれます。',missingFrontmatter:'YAML frontmatter がありません。',unterminatedFrontmatter:'frontmatter が正しく終了していません。',invalidYaml:'YAML frontmatter が無効です。',objectRequired:'YAML frontmatter はキーと値のオブジェクトである必要があります。',missingName:'frontmatter に name がありません。',missingDescription:'frontmatter に description がありません。' },
  'fr-FR': { scripts:'Cette Skill contient des scripts. Vérifiez-les avant l’installation.',binary:'Cette Skill contient des fichiers binaires non prévisualisables.',missingFrontmatter:'Le frontmatter YAML est absent.',unterminatedFrontmatter:'Le frontmatter n’est pas correctement terminé.',invalidYaml:'Le frontmatter YAML est invalide.',objectRequired:'Le frontmatter YAML doit être un objet clé-valeur.',missingName:'Le champ name manque dans le frontmatter.',missingDescription:'Le champ description manque dans le frontmatter.' },
  'ko-KR': { scripts:'이 Skill에는 스크립트 파일이 있습니다. 설치 전에 확인하세요.',binary:'이 Skill에는 미리 볼 수 없는 바이너리 파일이 있습니다.',missingFrontmatter:'YAML frontmatter가 없습니다.',unterminatedFrontmatter:'frontmatter가 올바르게 끝나지 않았습니다.',invalidYaml:'YAML frontmatter가 올바르지 않습니다.',objectRequired:'YAML frontmatter는 키-값 객체여야 합니다.',missingName:'frontmatter에 name이 없습니다.',missingDescription:'frontmatter에 description이 없습니다.' },
  'es-ES': { scripts:'Esta Skill contiene scripts. Revísalos antes de instalar.',binary:'Esta Skill contiene archivos binarios que no se pueden previsualizar.',missingFrontmatter:'Falta el frontmatter YAML.',unterminatedFrontmatter:'El frontmatter no termina correctamente.',invalidYaml:'El frontmatter YAML no es válido.',objectRequired:'El frontmatter YAML debe ser un objeto clave-valor.',missingName:'Falta name en el frontmatter.',missingDescription:'Falta description en el frontmatter.' },
  'pt-BR': { scripts:'Esta Skill contém scripts. Revise-os antes de instalar.',binary:'Esta Skill contém arquivos binários que não podem ser visualizados.',missingFrontmatter:'O frontmatter YAML está ausente.',unterminatedFrontmatter:'O frontmatter não foi encerrado corretamente.',invalidYaml:'O frontmatter YAML é inválido.',objectRequired:'O frontmatter YAML deve ser um objeto chave-valor.',missingName:'Falta name no frontmatter.',missingDescription:'Falta description no frontmatter.' },
  ar: { scripts:'تحتوي هذه Skill على ملفات نصية تنفيذية. راجعها قبل التثبيت.',binary:'تحتوي هذه Skill على ملفات ثنائية لا يمكن معاينتها.',missingFrontmatter:'بيانات YAML frontmatter مفقودة.',unterminatedFrontmatter:'لم يتم إنهاء frontmatter بشكل صحيح.',invalidYaml:'بيانات YAML frontmatter غير صالحة.',objectRequired:'يجب أن يكون YAML frontmatter كائن مفاتيح وقيم.',missingName:'الحقل name مفقود في frontmatter.',missingDescription:'الحقل description مفقود في frontmatter.' }
}

export function localizeSkillWarning(message: string, language: AppLanguage): string {
  const normalized = message.toLowerCase()
  let code: WarningCode | undefined
  if (normalized.includes('包含脚本文件') || normalized.includes('contains script')) code='scripts'
  else if (normalized.includes('二进制文件') || normalized.includes('binary file')) code='binary'
  else if (normalized.includes('缺少 yaml frontmatter') || normalized.includes('frontmatter is missing')) code='missingFrontmatter'
  else if (normalized.includes('没有正确结束') || normalized.includes('not properly terminated')) code='unterminatedFrontmatter'
  else if (normalized.includes('frontmatter 无效') || normalized.includes('frontmatter is invalid')) code='invalidYaml'
  else if (normalized.includes('必须是键值对象') || normalized.includes('key-value object')) code='objectRequired'
  else if (normalized.includes('缺少 name') || normalized.includes('missing name')) code='missingName'
  else if (normalized.includes('缺少 description') || normalized.includes('missing description')) code='missingDescription'
  return code ? warningMessages[language][code] : message
}

const sourceBrands: Record<string, string> = {
  'builtin-vercel-agent-skills':'Vercel Labs', 'builtin-anthropic-skills':'Anthropic', 'builtin-openclaw-skills':'OpenClaw', 'builtin-hermes-skills':'Hermes', 'builtin-openai-skills':'OpenAI', 'builtin-huggingface-skills':'Hugging Face', 'builtin-nvidia-skills':'NVIDIA', 'builtin-tencent-skillhub':'Tencent SkillHub', 'builtin-redskill':'REDnote Red Skill', 'builtin-modelscope-skills':'ModelScope Skills'
}
export function localizedSourceName(id: string, fallback: string, language: AppLanguage): string {
  const brand=sourceBrands[id]; if(!brand) return fallback
  if(id==='builtin-tencent-skillhub') return language==='zh-CN' ? '腾讯 SkillHub' : language==='zh-TW' ? '騰訊 SkillHub' : brand
  if(id==='builtin-redskill') return language==='zh-CN' ? '小红书 Red Skill' : language==='zh-TW' ? '小紅書 Red Skill' : language==='ja-JP' ? 'REDnote Red Skill' : brand
  if(id==='builtin-modelscope-skills') return brand
  const suffix: Record<AppLanguage,string>={ 'zh-CN':'官方技能','zh-TW':'官方技能','en-US':'Official Skills','ja-JP':'公式スキル','fr-FR':'Compétences officielles','ko-KR':'공식 스킬','es-ES':'Habilidades oficiales','pt-BR':'Habilidades oficiais',ar:'مهارات رسمية' }
  return id==='builtin-vercel-agent-skills' ? `${brand} ${language==='zh-CN'?'精选':language==='zh-TW'?'精選':language==='ja-JP'?'セレクション':'Selected'}` : `${brand} ${suffix[language]}`
}
export function localizedSourceDescription(id: string, fallback: string, language: AppLanguage): string {
  if(!sourceBrands[id]) return fallback
  const text: Record<AppLanguage,string>={
    'zh-CN':'官方精选 Skill 目录，支持搜索、预览与安装。','zh-TW':'官方精選 Skill 目錄，支援搜尋、預覽與安裝。','en-US':'Official curated Skill catalog with search, preview, and installation.','ja-JP':'検索、プレビュー、インストールに対応した公式 Skill カタログです。','fr-FR':'Catalogue officiel de Skills avec recherche, aperçu et installation.','ko-KR':'검색, 미리 보기 및 설치를 지원하는 공식 Skill 카탈로그입니다.','es-ES':'Catálogo oficial de Skills con búsqueda, vista previa e instalación.','pt-BR':'Catálogo oficial de Skills com busca, prévia e instalação.',ar:'دليل رسمي منسق للمهارات يدعم البحث والمعاينة والتثبيت.'
  }
  return text[language]
}

const fileCopy = {
  'zh-CN': ['删除 Skill','Skill 文件列表','技能内容','加载中','收起文件列表','展开文件列表','无文件','选择一个文件','{kind} 文件暂不支持预览','文件较大，已截断预览'],
  'zh-TW': ['刪除 Skill','Skill 檔案清單','技能內容','載入中','收合檔案清單','展開檔案清單','沒有檔案','選擇一個檔案','暫不支援預覽 {kind} 檔案','檔案較大，預覽已截斷'],
  'en-US': ['Delete Skill','Skill file list','Skill content','Loading','Collapse file list','Expand file list','No files','Select a file','{kind} files cannot be previewed','Large file; preview truncated'],
  'ja-JP': ['Skill を削除','Skill ファイル一覧','スキル内容','読み込み中','ファイル一覧を折りたたむ','ファイル一覧を展開','ファイルなし','ファイルを選択','{kind} ファイルはプレビューできません','大きなファイルのためプレビューを省略しました'],
  'fr-FR': ['Supprimer la Skill','Liste des fichiers Skill','Contenu de la Skill','Chargement','Réduire la liste','Développer la liste','Aucun fichier','Sélectionner un fichier','Aperçu indisponible pour les fichiers {kind}','Fichier volumineux, aperçu tronqué'],
  'ko-KR': ['Skill 삭제','Skill 파일 목록','스킬 내용','불러오는 중','파일 목록 접기','파일 목록 펼치기','파일 없음','파일 선택','{kind} 파일은 미리 볼 수 없습니다','큰 파일이라 미리 보기가 잘렸습니다'],
  'es-ES': ['Eliminar Skill','Lista de archivos de Skill','Contenido de la Skill','Cargando','Contraer lista','Expandir lista','Sin archivos','Seleccionar un archivo','No se pueden previsualizar archivos {kind}','Archivo grande; vista previa truncada'],
  'pt-BR': ['Excluir Skill','Lista de arquivos da Skill','Conteúdo da Skill','Carregando','Recolher lista','Expandir lista','Sem arquivos','Selecionar um arquivo','Arquivos {kind} não podem ser visualizados','Arquivo grande; prévia truncada'],
  ar: ['حذف Skill','قائمة ملفات Skill','محتوى المهارة','جار التحميل','طي قائمة الملفات','توسيع قائمة الملفات','لا توجد ملفات','اختر ملفا','لا يمكن معاينة ملفات {kind}','ملف كبير؛ تم اقتطاع المعاينة']
} satisfies Record<AppLanguage, string[]>
export function skillFileCopy(language: AppLanguage) {
  const [deleteSkill,fileList,content,loading,collapse,expand,empty,select,unsupported,truncated]=fileCopy[language]
  return { deleteSkill,fileList,content,loading,collapse,expand,empty,select,unsupported,truncated }
}
